services:
  mysql :
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=portfolio'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3308:3306'
